package:
    type:           yii2-extension
    name:           yii2-asset-ahnames
    title:          'AHnames asset files: images, configs and more'
    headline:       AHnames assets
    keywords:       ahnames, asset, extension, yii2
    namespace:      ahnames\assets\ahnames
    description:    |
        [AHnames](https://ahnames.com) is a domain registrator.

        This package provides assets shareable between different AHnames projects:

        - logos and css bundled with yii2 asset bundle
        - config settings
        - translations

require:
    hiqdev/hidev-php:     "*"
    ahnames/hidev-vendor: "*"
