package:
    name:           yii2-asset-ahnames
    namespace:      ahnames\assets\ahnames
    title:          Yii 2 asset with AHnames logos and so on
    type:           yii2-extension
    keywords:       ahnames, asset, extension, yii2
    year:           2015

require:
    ahnames/hidev-config:       "*"
    hiqdev/hidev-config-php:    "*"
